version: '3.8'

services:
  app:
    build:
      context: ./backend
    container_name: todo-app
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: clapping_system
      DB_USER: your_username
      DB_PASSWORD: your_password
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: ["sh", "-c", "/wait-for-it.sh postgres:5432 -- npm start"]
    restart: always

  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: clapping_system
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres-data:
