version: "3.8"

services:
  app:
    build:
      context: ./backend
    container_name: todo-app
    environment:
      NODE_ENV: development
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: clapping_system
      DB_USER: your_username
      DB_PASSWORD: your_password
      CHOKIDAR_USEPOLLING: "true" # Ensures file change detection in Docker
      CHOKIDAR_INTERVAL: "100" # Polling interval for fast reloads
    ports:
      - "4100:4000" # GraphQL API
      - "9229:9229" # Debugging
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
      - /app/node_modules # Prevents node_modules conflicts
    command: ["sh", "-c", "/wait-for-it.sh postgres:5432 -- npm run dev"]
    restart: unless-stopped # Avoids infinite restarts on failure

  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: clapping_system
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres-data:
